In [2]:
import numpy as np

### Creating a Numpy Array

We can create numpy arrays in various different ways. Some of them are as follows :

1. linspace
2. zeros
3. ones
4. ones_like
5. random.randn

In [9]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
x2 = np.zeros((2,3))
x2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones_like(x2)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.random.randn(2,2)

array([[-0.84155657,  0.41472227],
       [-0.15957261,  1.15917757]])

In [15]:
np.array([1,2,3])

array([1, 2, 3])

### dtype and shape

In [18]:
print(f'dtype attribute of x2 is : {x2.dtype}')
print(f'shape attribute of x2 is : {x2.shape}')

dtype attribute of x2 is : float64
shape attribute of x2 is : (2, 3)


In [24]:
# casting from one dtype to another
x = np.array([1,2,3])
print(f'initially dtype of x is : {x.dtype}')
x = x.astype(np.float)
print(f'now dtype of x is : {x.dtype}')

initially dtype of x is : int64
now dtype of x is : float64


In [22]:
x.dtype

dtype('int64')

In [25]:
x.shape

(3,)

### Arthimetic with Numpy Arrays

Any arthimetic operations between equal size arrays implies element wise operations

In [7]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr+arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [9]:
arr*arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

Arthimetic operations with scalars propagate the scalar arguement to all elements of the array

In [10]:
1/arr

<ipython-input-10-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([[       inf, 1.        , 0.5       ],
       [0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     ]])

In [11]:
arr**0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

### Basic Indexing and Slicing

Array slices are views on the original array and any changes to them will reflect in the original source array

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[5:8] = -1
arr

array([ 0,  1,  2,  3,  4, -1, -1, -1,  8,  9])

In [16]:
arr2d = np.arange(10).reshape((2,5))
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
arr2d[1]

array([5, 6, 7, 8, 9])

In [20]:
arr2d[0,4]

4